# Generated by Django 6.0.6 on 2026-06-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disease Category',
                'verbose_name_plural': 'Disease Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('risk_factors', models.TextField(blank=True)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField()),
                ('complications', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='diseases.diseasecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
